# Site
repository: tarekgabarin/resume_site
# favicon: images/favicon.ico

# Personal info
name: Tarek Gabarin
title: Front End Developer 
email: tarekgabarin1992@gmail.com

# Social links
github_username:  tarekgabarin
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: tarek-gabarin-8b216a151
# pinterest_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Tarek and I'm a web developer, working and living in Toronto. Currently looking for opportunities to build software solutions to real-world problems. 

  I am skilled in: <mark>React</mark> <mark>AngularJS</mark> <mark>JavaScript (ES8)</mark> <mark>Python 3</mark> <mark>HTML</mark> <mark>CSS</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering some of my other interests and hobbies are:
   - Creative writing
   - Gaming
   - Painting

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
